### ISSUE TITLE
Error: error sending request for url (http://localhost:8080/api/login): connection closed before message completed

### ISSUE THREAD

**Issue by chase-lambert** [jeremychone/rust-httpc-test#1]
Hello,

I am going through your great Axum course on Youtube and keep running up against this problem while trying to run the tests. It doesn't happen on the first test you go through (so the simple hello get request works as intended) but all the other ones after that have this issue. Using the old school `curl` approach to test the server works correctly as well. 

I think it might have something to do with this hyper issue: https://github.com/hyperium/hyper/issues/2136 but that's just a guess as you say this library is built on top of reqwest (which uses hyper right?). 

Any clue how to overcome this issue? I like this workflow and would like to use it while developing my own projects. My apologies if this is something related to my system and nothing to do with your library.

p.s. Crates.io has the wrong repository link. It tried to take me here: https://github.com/rust-httpc-test

**Comment by jeremychone** [comment]
Can you do a cargo update and make sure you use Axum 0.12.16 or above. There was a bug in the static routing that caused such issue when requesting a static file. 

Otherwise, I am not sure what it is. Will try to look at it, but it has been working pretty well on my side. 

Yes, it is using reqwest.

**Comment by chase-lambert** [comment]
That worked! Thank you and thanks for the great material you are putting out on YT. 0.6.15 -> 0.6.16
