### ISSUE TITLE
Allow a custom reqwest::Client, or ClientBuilder configuration hook

### ISSUE THREAD

**Issue by andsnpl** [jeremychone/rust-httpc-test#12]
I want to test redirection from my /login endpoint, but the default client created inside of `new_client` automatically follows redirects, so I don't get to inspect it.

**Comment by jeremychone** [comment]
This is a good one, let me work on this.

**Comment by jeremychone** [comment]
@andsnpl I just merge the two PRs, that should solve your requirement. Let me know if I can close this ticket. 

- Thanks to [@JamesGuthrie](https://github.com/JamesGuthrie) for 
	- [PR #17 + Allow building client with custom reqwest::ClientBuilder](https://github.com/jeremychone/rust-httpc-test/pull/17)
	- [PR #16 + Make rustc_http::Client public](https://github.com/jeremychone/rust-httpc-test/pull/16)

**Comment by jeremychone** [comment]
Closing as should be fixed with the PR above merged in the previous release.
