### ISSUE TITLE
Unable to test multipart/form-data requests with httpc-test

### ISSUE THREAD

**Issue by a-rustacean** [jeremychone/rust-httpc-test#13]
## Issue Description:

I'm currently working on a Rust backend using Actix Web, where I have implemented a POST route to handle multipart/form-data requests for saving images to disk. However, I'm encountering challenges when testing this functionality using the httpc-test library.

## Issue Description:

I've created a POST route that handles multipart/form-data requests and saves images to disk, but I'm struggling to find documentation or examples on how to effectively test this route using httpc-test. I've also explored the httpc-test source code but couldn't find any solutions that suit my needs.

## Request for Help:

I'm looking for guidance or examples on how to test this multipart/form-data request using httpc-test properly. Additionally, I already know how to do this using cURL, and the cURL command I use is as follows:

```shell
curl -F image=@image.jpg http://localhost:8080/post --trace-ascii
```

I want a similar functionality using httpc-test

Thank you for your help in advance!

**Comment by jeremychone** [comment]
Now, we exposed the `.reqwest_client()` and `.client_store()` as per your suggestion, so, should be ok. See #[77cedfb](https://github.com/jeremychone/rust-httpc-test/commit/77cedfb0725b46a5868bda2f3c5013f32915d614)

Feel free to open a new ticket if something is still missing.
