### ISSUE TITLE
new_client builder with headers

### ISSUE THREAD

**Issue by cody-why** [jeremychone/rust-httpc-test#19]
some test need
header 
cookie
how about add client builder?

**Comment by cody-why** [comment]
I've added a method to client.rs

```rust
pub async fn capture_response2(
	&self,
	request_method: impl AsRef<str>,
	reqwest_res: reqwest::Response,
) -> Result<Response> {
	let request_method = Method::from_bytes(request_method.as_ref().as_bytes()).unwrap();
	let url = reqwest_res.url().to_string();
	self.capture_response(request_method, url, reqwest_res).await
}
```

test

```rust
    let hc = httpc_test::new_client("http://localhost:8080").unwrap();
    let rb = hc.reqwest_client().post("/test").header("sign", "xxx");

    let res = rb.send().await?;
    hc.capture_response2("POST", res).await?.print().await?;
```

**Comment by jeremychone** [comment]
interesting, I might rename this function, but I like the concept. 

let me look at it.

**Comment by jeremychone** [comment]
hum, I am confused, rhe `hc.reqwest_client() -> &reqwest::Client ` do not have the base URL, so, I am not sure what the `hc.reqwest_client().post("/test")` will post to which host.

**Comment by cody-why** [comment]
yes, it need combine base URL...
> ```rust
> hc.reqwest_client().post("http://localhost:8080/test").header("sign", "xxx");
> ```

**Comment by jeremychone** [comment]
ok, I think I need to find another way. But thanks a lot for sharing.
