### ISSUE TITLE
issue if using reqwest v0.12.0 and above

### ISSUE THREAD

**Issue by SniffleSneeze** [jeremychone/rust-httpc-test#22]
Hi everyone,  
I've recently started to use that great library after watching on of your video @jeremychone  and I love it.
However in my case some of my testing required me to set the header for auth
therefor I've use the `reqwest_builder` i.e. `reqwest::ClientBuilder` to be use in conjonction with the `httpc_test::new_client_with_reqwest`.
So far so good, however the issue I want to raise is that for what ever reason if you use a version of `reqwest v12` and above  you receive that annoying: 

> expected `ClientBuilder`, found a different `ClientBuilder`

I fafed around with different version and everything work fine until you chose v0.12.0 
 Max supported is v0.11.27.
 
Thanks for your great work and I hope I'm writting this in the right place.

Alex

**Comment by jeremychone** [comment]
@SniffleSneeze Sorry for this forever delay. I finally merged @joeftiger PR that should fix the issue.
