### ISSUE TITLE
PUT elicits a POST

### ISSUE THREAD

**Issue by snarkipus** [jeremychone/rust-httpc-test#4]
Great little tool - I came across it in your Axum video (which is also amazing).

Using it some scratch integration, I noticed that PUTs would fail with records already existing - poking around, it looks like it calls the request::post method instead of request::put under the hood.

**Comment by jeremychone** [comment]
oops, let me check.

**Comment by jeremychone** [comment]
Ho yes, the `PUT` was correct, but the `PATCH` was wrong. 
![image](https://github.com/jeremychone/rust-httpc-test/assets/74671/3df86d51-eda5-4ec9-bc11-82c67f6a11e8)

Fixing that now.

**Comment by jeremychone** [comment]
So, I solve the #5, where `patch` was mapped to `put`. However, `put` seems to have been mapped to `post`. Let me know if I missed something.

**Comment by jeremychone** [comment]
Closing this one. As the issue was with `patch` I think and was fixed in #5.
